use super::{Fields, base_int_lines, join_blocks, substitute};

const HEADER: &str = r#"/** This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/krakjn/bump
 */

#ifndef BUMP_VERSION_H
#define BUMP_VERSION_H
"#;

const FOOTER: &str = r#"
#endif /* BUMP_VERSION_H */
"#;

pub(crate) fn render(fields: &Fields) -> String {
    let prefix = substitute(
        "#define {emit_prefix}{case_prefix} \"{version_prefix}\"",
        fields,
    );
    let base = base_int_lines(fields, |prefix, c| {
        format!("#define {prefix}{} {}", c.case_name, c.value)
    });
    let tail = substitute(
        r#"#define {emit_prefix}{case_phase} "{version_phase}"
#define {emit_prefix}{case_phase_distance} {version_phase_distance}
#define {emit_prefix}{case_string} "{version_string}"
#define {emit_prefix}{case_timestamp} "{version_timestamp}""#,
        fields,
    );
    let body = join_blocks(&[&prefix, &base, &tail]);
    format!("{HEADER}\n\n{body}{FOOTER}")
}
