use super::{Fields, substitute};
use crate::version::VersionMode;

const SEMVER: &str = r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/krakjn/bump
 */

public static class Version {
    public const string {emit_prefix}{case_prefix} = "{version_prefix}";
    public const int {emit_prefix}{case_major} = {version_major};
    public const int {emit_prefix}{case_minor} = {version_minor};
    public const int {emit_prefix}{case_patch} = {version_patch};
    public const string {emit_prefix}{case_phase} = "{version_phase}";
    public const int {emit_prefix}{case_phase_distance} = {version_phase_distance};
    public const string {emit_prefix}{case_string} = "{version_string}";
    public const string {emit_prefix}{case_timestamp} = "{version_timestamp}";
}
"#;

const CALVER: &str = r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/krakjn/bump
 */

public static class Version {
    public const string {emit_prefix}{case_string} = "{version_string}";
    public const string {emit_prefix}{case_timestamp} = "{version_timestamp}";
}
"#;

pub(crate) fn render(fields: &Fields) -> String {
    match fields.version_mode {
        VersionMode::Semver => substitute(SEMVER, fields),
        VersionMode::Calver => substitute(CALVER, fields),
    }
}
