use super::{Fields, base_int_lines, join_blocks, substitute};

const HEADER: &str = r#"// This file is generated by:
//  ____  __  __  __  __  ____ 
// (  _ \(  )(  )(  \/  )(  _ \
//  ) _ < )(__)(  )    (  )___/
// (____/(______)(_/\/\_)(__)  
//
// https://github.com/krakjn/bump

package version

const (
"#;

const FOOTER: &str = "\n)\n";

pub(crate) fn render(fields: &Fields) -> String {
    let prefix = substitute(
        "\t{emit_prefix}{case_prefix} = \"{version_prefix}\"",
        fields,
    );
    let base = base_int_lines(fields, |prefix, c| {
        format!("\t{prefix}{} = {}", c.case_name, c.value)
    });
    let tail = substitute(
        r#"\t{emit_prefix}{case_phase} = "{version_phase}"
\t{emit_prefix}{case_phase_distance} = {version_phase_distance}
\t{emit_prefix}{case_string} = "{version_string}"
\t{emit_prefix}{case_timestamp} = "{version_timestamp}""#,
        fields,
    );
    let body = join_blocks(&[&prefix, &base, &tail]);
    format!("{HEADER}{body}{FOOTER}")
}
