use super::{Fields, base_int_lines, join_blocks, substitute};

const HEADER: &str = r#"/**
 * This file is generated by:
 *  ____  __  __  __  __  ____ 
 * (  _ \(  )(  )(  \/  )(  _ \
 *  ) _ < )(__)(  )    (  )___/
 * (____/(______)(_/\/\_)(__)  
 *
 * https://github.com/krakjn/bump
 */

public class Version {
"#;

const FOOTER: &str = "}\n";

pub(crate) fn render(fields: &Fields) -> String {
    let prefix = substitute(
        "    public static final String {emit_prefix}{case_prefix} = \"{version_prefix}\";",
        fields,
    );
    let base = base_int_lines(fields, |prefix, c| {
        format!(
            "    public static final int {prefix}{} = {};",
            c.case_name, c.value
        )
    });
    let tail = substitute(
        r#"    public static final String {emit_prefix}{case_phase} = "{version_phase}";
    public static final int {emit_prefix}{case_phase_distance} = {version_phase_distance};
    public static final String {emit_prefix}{case_string} = "{version_string}";
    public static final String {emit_prefix}{case_timestamp} = "{version_timestamp}";"#,
        fields,
    );
    let body = join_blocks(&[&prefix, &base, &tail]);
    format!("{HEADER}{body}\n{FOOTER}")
}
